### ISSUE TITLE
The accuracy of TSM-SELFY-R18/R50  on sth-sth v1

### ISSUE THREAD

**Issue by whwu95** [arunos728/SELFY#1]
Hi, I have downloaded your official codes to reproduce the results of TSM-SELFY-R18 and R50 on the something-v1 dataset. 
My top-1 accuracy of the R18 model is 42.6%, which is 48.4% in your paper. 
And the top-1 accuracy of the R50 model is 48.3%, which is 52.5% in your paper.
Attached are my log files.
Did I get something wrong?
[selfy-tsm50.log](https://github.com/arunos728/SELFY/files/7490817/selfy-tsm50.log)
[selfy-tsm18.log](https://github.com/arunos728/SELFY/files/7490818/selfy-tsm18.log)

**Comment by whwu95** [comment]
To verify the effectiveness of the SELFY model, I also conduct the experiment on TSM-R18 and get the same results with SELFY-TSM counterpart. This SEFLY module does not seem to provide performance improvements. 

So I check your codes and comparison with the official TSM codebases. I find you changed the data augmentation (e.g., **selective Flip**, **resize images to 240x320**). I just simply add these two augmentations to the original TSM, then get an unbelievable strong TSM baseline (+2% on sth-sthv1).

**Comment by arunos728** [comment]
Hello whwu95,
It seems that the result of your selfy-TSM18 is similar to the result of TSM18 in our paper (Table 4b), which means SELFY block does not work in your result.
I think that 'Spatial Correlation Sampler' does not work in your code, so could you try again after modifying line14 of  [selfy.py](https://github.com/arunos728/SELFY/blob/master/ops/selfy.py) from 'use_corr_sampler=True' to 'use_corr_sampler=False'?
This is a modification about computing self-similarity without using 'Spatial Correlation Sampler'.

Thanks for your attention.
Please let me know if you need any help.

**Comment by whwu95** [comment]
> Hello whwu95, It seems that the result of your selfy-TSM18 is similar to the result of TSM18 in our paper (Table 4b), which means SELFY block does not work in your result. I think that 'Spatial Correlation Sampler' does not work in your code, so could you try again after modifying line14 of [selfy.py](https://github.com/arunos728/SELFY/blob/master/ops/selfy.py) from 'use_corr_sampler=True' to 'use_corr_sampler=False'? This is a modification about computing self-similarity without using 'Spatial Correlation Sampler'.
> 
> Thanks for your attention. Please let me know if you need any help.

Yes, I have utilized the 'use_corr_sampler=False', but I get only 51.467% on sthv1, which is 52.5% on the paper.
Also, I got 63.45% on sthv2, which is 64.5% on the paper. 
Attached is my log file. Did I get something wrong?
[SELFY-R50-TSM-log.txt](https://github.com/arunos728/SELFY/files/7616505/SELFY-R50-TSM-log.txt)

**Comment by mm840511m** [comment]
Hi @whwu95,
According to the log files you provided, I encountered the same error message that you also had. How can I solve this error? Thank you.

FileNotFoundError: [Errno 2] No such file or directory: '/home/something-something-v2/frames/177891/img_00003.jpg'
FileNotFoundError: [Errno 2] No such file or directory: '/home/something-something-v2/frames/13376/img_00002.jpg'

Here's my log file :
[log.txt](https://github.com/arunos728/SELFY/files/9485986/log.txt)
